document.writeln("<div class=\'Middle\'>");
document.writeln("            <div class=\'footer\'>");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <h3>关于我们</h3>");
document.writeln("                        <a href=\'About.html?id=5\'>简介</a>");
document.writeln("                        <a href=\'Contact.html?id=6\'>联系我们</a>");
document.writeln("                        <a href=\'Contact.html?id=6\'>加入我们</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <h3>产品中心</h3>");
document.writeln("                        <a href=\'Produc01_02.html?type=2\'>木工坊</a>");
document.writeln("                        <a href=\'Product.html?id=2&type=11\'>炭烧积木</a>");
document.writeln("                        <a href=\'Product.html?id=2&type=22\'>区角</a>");
document.writeln("                        <a href=\'Product.html?id=2&type=33\'>游乐设施</a>");
document.writeln("                        <a href=\'Produc07_03.html?type=2\'>运动包</a>");
document.writeln("                        <a href=\'Produc07_01.html?type=2\'>福禄贝尔</a>");
document.writeln("                        <a href=\'Produc07_02.html?type=2\'>蒙特梭利</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <h3>企业文化</h3>");
document.writeln("                        <a href=\'Culture.html?id=3\'>教育理念</a>");
document.writeln("                        <a href=\'Culture.html?id=3&type=55\'>企业愿景</a>");
document.writeln("                        <a href=\'Culture.html?id=3&type=66\'>品牌定位</a>");
document.writeln("                        <a href=\'Culture.html?id=3&type=77\'>企业使命</a>");
document.writeln("                        <a href=\'Culture.html?id=3&type=88\'>服务理念</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <h3>资讯信息</h3>");
document.writeln("                        <a href=\'Activityc.html?id=4\'>园长论坛</a>");
document.writeln("                        <a href=\'Activityc.html?id=4\'>幼教展</a>");
document.writeln("                        <a href=\'Activityc.html?id=4\'>学术研究</a>");
document.writeln("                        <a href=\'Activityc.html?id=4\'>其他</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <h3>关注我们</h3>");
document.writeln("                        <img src=\'images/section4_02.png\' /><br/>");
document.writeln("                        <div class=\'footerR\'>");
document.writeln("                            <span>全国免费<br/>咨询热线</span>");
document.writeln("                            <span><img style=\'position: relative; bottom: -20px;left: -20px;\' src=\'images/section4_01.png\' /></span>");
document.writeln("                        </div>");
document.writeln("                        <h3>400 - 1800 - 333</h3>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");